"""empty message

Revision ID: a4982c11597c
Revises: 
Create Date: 2017-01-11 14:41:01.347384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4982c11597c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
